name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn --immutable

      - name: Lint files
        run: yarn lint

      - name: Build
        run: yarn build

      # - name: Test
      #   run: yarn test --collectCoverage

      # - name: Upload Code Coverage
      #   run: bash <(curl -s https://codecov.io/bash)
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
